<a href="https://colab.research.google.com/github/lichengiggs/AIPNDCapstone-cn/blob/master/is_baba_fake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
#双11的第几个年头
year = [2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
x = [1,2,3,4,5,6,7,8,9,10,11]

#每年的销售额（亿元）
y = [0.5,9.36,52,191,350,571,912,1207,1682.69,2135,2684]


In [0]:
#给前N年的数据，推出后面几年的销售量
def predict_sales(x, y, num):
    x_years = x[0:num]
    y_years = y[0:num]
    
    #第三个参数2，表明用的是二元多项式
    coef = np.polyfit(x_years, y_years, 2)
    model = np.poly1d(coef)

    #返回预测值和实际值，作为比较
    return model(x[num:]), y[num:], coef

In [44]:
for num in range(3,11):
    print('##use 2009-{} to predict year:{}-{}##'.format(year[num-1], year[num], year[-1]))
    predict, fact, coef = predict_sales(x, y, num)
    print(predict)
    print('\n')

##use 2009-2011 to predict year:2012-2019##
[ 128.42  238.62  382.6   560.36  771.9  1017.22 1296.32 1609.2 ]


##use 2009-2012 to predict year:2013-2019##
[ 379.425  636.049  957.743 1344.507 1796.341 2313.245 2895.219]


##use 2009-2013 to predict year:2014-2019##
[ 583.084       869.468      1212.51485714 1612.22457143 2068.59714286
 2581.63257143]


##use 2009-2014 to predict year:2015-2019##
[ 851.342      1184.03114286 1571.22528571 2012.92442857 2509.12857143]


##use 2009-2015 to predict year:2016-2019##
[1262.02       1688.20857143 2176.12333333 2725.76428571]


##use 2009-2016 to predict year:2017-2019##
[1626.31107143 2086.71583333 2604.26178571]


##use 2009-2017 to predict year:2018-2019##
[2143.0947619  2683.19228571]


##use 2009-2018 to predict year:2019-2019##
[2675.907]




In [120]:
#用特征工程的方法做一个x^2的参数，然后用线性拟合来完成
#summary有详细的统计学参数，供想详细了解的同学使用，反正我不懂
import numpy as np
import pandas as pd
import statsmodels.api as sm

num = 10
tmp = {'price':pd.Series(y[:num]), 'x':pd.Series(x[:num]), 'x**2':pd.Series(np.power(x[:num],2))}
df = pd.DataFrame(tmp)
df['intercept'] = 1
Y = df['price']
X = df[['intercept', 'x', 'x**2']]
lm = sm.OLS(Y, X)
result = lm.fit()
result.summary()

/Users/luffy/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1450: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                     5614.
Date:                Tue, 12 Nov 2019   Prob (F-statistic):           6.04e-12
Time:                        22:30:44   Log-Likelihood:                -43.005
No. Observations:                  10   AIC:                             92.01
Df Residuals:                       7   BIC:                             92.92
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     70.3863     25.083      2.806      0.026      11.075     129.698
x            -94.1803     10.476     -8.990      0.000    -118.951     -69.409
x**2          30.0951      0.928     32.427      0.000      27.900      32.290
==============================================================================
Omnibus:                        0.473   Durbin-Watson:                   3.537
Prob(Omnibus):                  0.789   Jarque-Bera (JB):                0.289
Skew:                          -0.345   Prob(JB):                        0.866
Kurtosis:                       2.534   Cond. No.                         202.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [119]:
#用sklearn做了另外一个，可以看到预测值
from sklearn.linear_model import LinearRegression

num = 10
tmp = {'price':pd.Series(y[:num]), 'x':pd.Series(x[:num]), 'x**2':pd.Series(np.power(x[:num],2))}
df = pd.DataFrame(tmp)
Y = df['price']
X = df[['x', 'x**2']]

lm = LinearRegression().fit(X,Y)
print(lm.coef_, lm.intercept_)

pred_X = pd.DataFrame({'x':pd.Series(x[num:]), 'x**2':pd.Series(np.power(x[num:],2))})
lm.predict(pred_X), y[num:]

[-94.18031818  30.09507576] 70.38633333333257


(array([2675.907]), [2684])